const router = require("express").Router();

const cloudinary = require("cloudinary").v2;

router.get("/", async (req, res) => {
  await cloudinary.uploader.upload(
    "teste.jpg",
    { public_id: "tcc/teste", overwrite: true },
    function (err, image) {
      console.log();
      console.log("** File Upload");
      if (err) {
        console.warn(err);
      }
      console.log(
        "* public_id for the uploaded image is generated by Cloudinary's service."
      );
      console.log("* " + image.public_id);
      console.log("* " + image.url);
      waitForAllUploads("pizza", err, image);
    }
  );
});

module.exports = (app) => {
  app.use("/upload", router);
};
